product-os/scripts

shared/pip-dependencies.sh

Signed-off-by: Jack Brown <jack@resin.io>

pip: Ignore dependencies installed via easy_install

---

shared/npm-install.sh

This prevents failures due to the nounset option being enabled.
Fixes https://github.com/balena-io/scripts/issues/7

Ensure AWS secret variables are defined

---

npm/should-store.sh
npm/store.sh
shared/is-npm.sh

Also exclude electron applications from is-npm checks as those will meet
all the requirements to qualify as an npm project

Add should-store script that checks if package.json sets private: true

---

electron/install.sh

This is needed for us to check dependencies before we generate the code bundle, which is in a separate step
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzothunder.ambrosi@gmail.com>

Add skip option for concourse-build-electron

---

electron/electron-builder.json

Use the electron-builder defaults or add it to .resinci.json in your
project.

Don't specify a default "files" section for electron-builder

---

npm/store.sh

Signed-off-by: Tomás Tormo <tomast@balena.io>

Add support for granting readonly permissions to a given npm team for a private package

---

docker/build.sh

Check for null string as that is what the current version of jq returns
when the field is missing

Fix repo check in docker build task

---

electron/electron-builder.json

Fix libpango deb package name for electron

---

ci-checks/should-build-branch.sh

than expect only backport commits

Update base-branch check to check if branch is declared as ESR rather

---

ci-checks/check-commits.sh
ci-checks/check-license.sh
npm/store.sh

And the path has indeed changed from `/usr/bin/egrep` to `/bin/egrep` with the updated alpine in newer nodejs images

Use `egrep` rather than `/usr/bin/egrep` for resilience to path changes

---

docker/build.sh

Avoids the test AWS credentials variables from being unset.
Signed-off-by: Carlo Miguel Cruz <carloc@balena.io>

Docker Build Script: Unset Concourse AWS keys before loading variables.

---

electron/electron-builder.json

Remove libappindicator1 debian dependency for electron

---

npm/store.sh

Set npm token in publish job so it can pull private modules if needed

---

npm/store.sh

Set npm unsafe perm to prevent errors in prepack script

---

npm/store.sh

Also inverts the logic so that we default to considering the repo private and only set it to public when we can fetch its homepage on github

Fix curl check to see if a repo is private for npm/store

---

docker/store.sh

Branch tag was previously pushed as is. This meant if someone had named a branch as `vX.Y.Z`, it would be tagged and pushed as such. It would then be picked up by flux and deployed. The branch tag is mostly used for testing, so renamed with a "build" prefix. Also removed an unused `latest` tag.

Prefix branch tag

---

docker/build.sh

When building a docker image, scan the image with [trivy](https://github.com/aquasecurity/trivy) just after tagging it. This is only for showing the output, build won't fail based on `trivy` results (yet).  An example of how this can look on a concourse build:
```
+ trivy --no-progress --exit-code 0 --severity HIGH --ignore-unfixed balenaci/vb-test:latest
2021-05-11T21:08:27.261Z	INFO	Need to update DB
2021-05-11T21:08:27.261Z	INFO	Downloading DB...
2021-05-11T21:08:29.760Z	INFO	Detecting Alpine vulnerabilities...
2021-05-11T21:08:29.761Z	INFO	Trivy skips scanning programming language libraries because no supported file was detected
balenaci/vb-test:latest (alpine 3.11.5)
=======================================
Total: 11 (HIGH: 11) …
```

Scan docker image with trivy

---

docker/build.sh

This reverts commit ba4cad3d06ded37b816f978ddea04e5a678c3441.
The original merge was causing an issue with JF builds. `GITHUB_TOKEN` was clashing the the JF one. JF var has now been removed.

Revert "Revert "Scan docker image with trivy""

---

docker/build.sh

For a period of time, we will be collecting trivy vulnerabilities and sending them to AWS, to see what kind of errors are out there, and fix them, before turning trivy on. This is a temporary change, and will be reverted/update when we have enough data.

Collect trivy metrics

---

docker/build.sh

Use sha as filename to avoid filename collision in parallel builds

---

docker/build.sh

trivy can sometimes fail for various reasons. This should not cause the whole build to fail, as it's a tool we temporarily installed for getting vulnerability metrics.

Prevent trivy from failing the build

---

docker/build.sh
docker/image-cache.sh
docker/store.sh

Requires buildx for building multiarch manifests
and skopeo for copying images between the CI image
cache and the external registries.
Resolves: https://github.com/product-os/scripts/issues/155
Depends-on: https://github.com/product-os/ci-images/pull/100
Depends-on: https://github.com/product-os/balena-concourse/pull/618
Signed-off-by: Kyle Harding <kyle@balena.io>

Support for building multiarch docker images

---

docker/build.sh

ci-pipeline raised issue:
```
2022-05-10T12:51:26.815Z	WARN	Increase --timeout value
2022-05-10T12:51:26.815Z	FATAL	scan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded
```
Correct typo of trivy timeout argument (-- doubledash)

Increase trivy timeout

---

docker/build.sh
shared/resinci-read.sh

Split parallel builts into context of single build paths.
Should be downwards compatible and should work with empty path key

Split docker builds into single parallel context

---

docker/build.sh

Wait for builds when they are pendning after starting

Fix parallel build limiter

---

docker/build.sh

The build context ceases and ends with `deadline exceed`
This is observable on a busy CI.

Docker buildx parallel builds fail
