shared/npm-install.sh

Useful when running this locally.

shared: Add flag to bypass cache upload on npm-install

---

types/is-docker.sh
types/is-npm.sh

Add is-docker and is-npm scripts from Concourse

---

shared/is-master.sh
shared/is-pr.sh

Add is-master and is-pr scripts

---

electron/electron-builder.sh
electron/install.sh
electron/test.sh

electron: Backport various fixes from resin-concourse

---

repo.yml

Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzothunder.ambrosi@gmail.com>

Add repository type in repo.yml

---

electron/electron-builder.sh

Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzothunder.ambrosi@gmail.com>

Ignore by default electron-builder unresolved dependencies

---

electron/package.sh
electron/test.sh

Add package scripts

---

shared/architecture-convert.sh

Signed-off-by: Carlo Maria Curinga carlo@balena.io

add aarch64 to arm64 handling

---

electron/install.sh

Remove darwin test and chown from electron install.sh

---

electron/install.sh
electron/package.sh
electron/test.sh

Refactor electron scripts

---

ci-checks/base-is-master.sh
ci-checks/check-commits.sh
ci-checks/check-license.sh
ci-checks/check-readme.sh

Add ci-checks

---

ci-checks/check-license.sh

Remove extra logging in license check

---

ci-checks/check-commits.sh

Do not install ci tools as they are included in the base image

---

shared/is-docker.sh
shared/is-electron.sh
shared/is-npm.sh
shared/is-rust.sh
shared/is-type.sh

Add discriminant scripts

---

ci-checks/check-license.sh

Check if PR is fork in check-license

---

npm/store.sh

Add npm/store script

---

electron/install.sh
node-cli/test.sh
shared/ensure-npm-valid-dependencies.sh
shared/ensure-staged-shrinkwrap.sh
shared/sanity-checks.sh

Take NPM_VERSION as a command line argument

---

npm/store.sh
shared/is-npm.sh

Signed-off-by: Giovanni Garufi <nazrhom@gmail.com>

Only check private key in pkg.json before store-npm

---

shared/is-npm.sh

Signed-off-by: Gergely Imreh <gergely@balena.io>

is-npm: only run repo.yml-based checks if file exists

---

shared/is-npm.sh

Exclude all non-node project types from is-npm

---

shared/protect-branch.sh

Add protect branch script

---

github/store-github.sh

Add store-github script

---

github/store-github.sh

This is an experimental feature, it will not do anything on repos that
do not have a contract template

Attempt to generate contracts and store them in build branch

---

deploy/deploy.sh
deploy/keyframes.sh
deploy/should-deploy.sh

Add deploy, shoud deploy and keyframes scripts

---

shared/apply-patches.sh

Signed-off-by: Matthew McGinn <matthew@balena.io>

patch: use glob instead of unstable ls output

---

docker/build.sh

Add docker build script

---

docker/build.sh

Remove template from script

---

docker/build.sh

Sanitise branch name before creating docker tag

---

deploy/landr.sh

Add landr deploy script

---

docker/build.sh

Add docker build args to docker build script

---

docker/build.sh

Pass args as empty string in default case

---

shared/is-npm.sh

Make is-npm pass for node-cli projects

---

shared/architecture-convert.sh

Replace arm -> armv7l

---

ci-checks/base-is-master.sh
ci-checks/check-commits.sh
ci-checks/check-license.sh
ci-checks/check-readme.sh
ci-checks/is-meta-pr.sh

Add taskinfo messages for check tasks

---

shared/is-docker.sh

Exclude docker builds if type is generic

---

ci-checks/base-is-master.sh

Build meta PRs targeting all branches

---

shared/is-docker.sh

Check if docker is set to run: false in discriminants

---

shared/is-docker.sh

Fix missing reference in is-docker script

---

electron/build.sh
electron/electron-builder.sh
electron/package.sh

Remove unused ARGV_TEMPORARY_DIRECTORY in electron scripts

---

electron/build.sh
electron/package.sh

Fix syntax errors introduced in a91300ef5630daf8099eca931aaa5941d9c6b1d1

---

shared/is-pr.sh

Exclude VersionEvent from is-pr

---

shared/is-pr.sh

Fix missing space in is-pr

---

meta/rebase.sh
shared/is-esr.sh
shared/is-master.sh
shared/is-pr.sh
shared/is-version-event.sh

Add rebase scripts

---

electron/test.sh

Run Xvfb with "-extension GLX" to prevent electron-mocha from segfaulting

---

meta/rebase.sh

Exclude auto-rebase from repo.yml

---

docker/build.sh

Build and push docker images in parallel

---

docker/build.sh

Wait for each parallel build individually so that errors get properly

---

github/store-github-release.sh
hardware/rfq.sh

Add hardware rfq and extract github release script

---

publish/backports.sh

Add backport script

---

npm/store.sh

Signed-off-by: Tomás Tormo <tomast@balena.io>

Do case insensitive matching when checking if a Github repo is private

---

CODEOWNERS

Add kaisoz to codeowners

---

balena/build.sh

Login with token before setting -x

---

docker/store.sh

Fix docker store job so that it references the latest tag

---

docker-compose/test.sh
docker/build.sh

Source files correctly in compose test and enforce docker_repo to be set

---

docker/build.sh

Prevent jq from erroring early if docker_repo is not found

---

docker/store.sh

Respect publish setting for docker image

---

docker/store.sh

Signed-off-by: Tomás Tormo <tomast@balena.io>

Fix docker containers not being published

---

docker/build.sh

Expose test npm token to docker build

---

hardware/rfq.sh

Signed-off-by: Ryan Cooke <ryan@balena.io>

Changed rfq.sh to reflect updated interface

---

electron/electron-builder.json

Don't depend on lsb rpm package for electron

---

ci-checks/check-license.sh

Only request github metadata information to limit number of github api

---

electron/test.sh

Change electron tests Xvfb resolution and color depth

---

shared/detect-event-type.sh

Add republish event

---

meta/rebase.sh

Modify rebase so that it will take up to 3 PRs to rebase

---

docker/build.sh

Source runtime secrets with chamber

---

docker/build.sh

Check if secret file if present

---

docker/build.sh

Remove secret file after sourcing env vars from it

---

docker/build.sh

Update runtime secret path with concourse prefix

---

docker/build.sh

Escape runtime secrets before loading them

---

shared/is-esr.sh

Add support to republish ESR branches

---

shared/is-docker.sh

Add balena type to excluded from docker build

---

hardware/is-type.sh
hardware/kicad-exports.sh

Signed-off-by: Ryan Cooke <ryan@balena.io>

add support for kicad exporting

---

docker/build.sh

Connects-to: https://github.com/balena-io/balena-cli/pull/2159
Signed-off-by: Kyle Harding <kyle@balena.io>

docker: register qemu binfmt for emulated arm docker builds

---

github/store-github.sh

Look for the balena.yml file only in root directory

---

docker/build.sh
docker/store.sh

* (e.g.) balena/open-balena-base:no-systemd-latest
Tested using open-balena-base: https://github.com/balenaci/open-balena-base/pull/5
* [balenaCI test build](https://ci.balena-dev.com/teams/main/pipelines/github-events-balenaci/jobs/docker/builds/26)
* [DockerHub assets](https://hub.docker.com/repository/docker/balena/open-balena-base/tags?page=1&ordering=last_updated)
* related [balena-concourse PR](https://github.com/product-os/balena-concourse/pull/578)

Enable building docker image variants

---

publish/annotate-source.sh

Add an error message when failing to find a build branch to publish

---

docker/build.sh

* checks for preset keys and tooling
* reveal secrets using git-secret.io workflow
* fix build args processing
* add Docker BuikdKit secrets handling (compatible with balena-secrets)

Add support for git-secret

---

docker/build.sh

* before trying to step through build stages, build without --taget parameter to ensure runtime stage, even if unlabeled, is built

Always build the last stage

---

docker/build.sh

* change the order to build the (default) runtime stage after multi-stage handling

Always build the last stage (#2)

---

balena/build.sh

* fix task script to correctly handle orgs
* correctly handle return code from balena_app_exists()

Add git-secrets support to balena task(s)

---

balena/build.sh

Add org name to balena push

---

docker/build.sh

This reverts commit 97e1cc39e566e7ccbf8b3f7f5192fc8af665a691.

Revert "Scan docker image with trivy"

---

docker/build.sh

Fix wrong trivy variable

---

docker/build.sh

Use epoch nano seconds instead of sha

---

docker/build.sh

Decrease trivy timeout

---

docker/build.sh

Add source repo to trivy API

---

build-in-container/run-build.sh
docker/build.sh
docker/store.sh

* refactor and shellcheck
* add registry mirror option

Add registry mirror parameter

---

build-in-container/run-build.sh
docker/build.sh
docker/store.sh

This reverts commit 55d2491120f6ec8d0a95f8c888c647cf66453417.

Revert "Add registry mirror parameter"

---

build-in-container/run-build.sh
docker/build.sh
docker/store.sh

This reverts commit 9bbbb5a39c8d17a56dc790801add25c46b96a059.

Revert "Revert "Add registry mirror parameter""

---

ci-checks/should-build-branch.sh
deploy/deploy.sh
docker/build.sh
docker/store.sh
meta/meta-declare-esr.sh
meta/meta-electron.sh
meta/rebase.sh
publish/backports.sh
rust/store-wasm-npm.sh
shared/is-docker.sh
shared/is-electron.sh
shared/is-esr.sh
shared/is-npm.sh
shared/is-type.sh
shared/resinci-read.sh
types/is-docker.sh

Use syntax compatible with latest yq version (4.11.2)
To be used with https://github.com/product-os/ci-images/pull/99

Upgrade yq version

---

ci-checks/should-build-branch.sh
deploy/deploy.sh
docker/build.sh
docker/store.sh
meta/meta-declare-esr.sh
meta/meta-electron.sh
meta/rebase.sh
publish/backports.sh
rust/store-wasm-npm.sh
shared/is-docker.sh
shared/is-electron.sh
shared/is-esr.sh
shared/is-npm.sh
shared/is-type.sh

yq syntax needs to be updated correctly for the 4.11.2 version

Fix yq eval syntax

---

docker/build.sh

Some docker-compose tests were expecting the image tagged
'latest' to be available so load that tag rather than
the branched tag.
Signed-off-by: Kyle Harding <kyle@balena.io>

Load latest tag after build to run compose tests

---

shared/ensure-staged-shrinkwrap.sh

Utilize jq to remove possible positional changes
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzothunder.ambrosi@gmail.com>

Fix shrinkwrap comparison script

---

balena-engine/build.sh

Connects-to: https://github.com/product-os/ci-images/pull/115
Signed-off-by: Robert Günzler <robertg@balena.io>

balena-engine: use new build target

---

hardware/rfq.sh

Signed-off-by: Anuj Deshpande <anuj@balena.io>

Pass release name to rfq tool

---

github/store-github-release.sh

See related PR - https://github.com/product-os/versionbot/pull/403

Move email sending from versionbot to CI

---

build-in-container/run-build.sh

Signed-off-by: Kyle Harding <kyle@balena.io>

Add missing parameters to start_docker

---

docker/build.sh

https://aquasecurity.github.io/trivy/v0.27.0/docs/references/cli/image/

Update trivy to 0.27.0 compatible command argument

---

docker/build.sh
shared/resinci-read.sh

Fixing docker build script changes

---

docker/build.sh

Testing serial docker builds

---

docker/build.sh

Parallel builds seem to exceed some buildkit context

Serial Docker Builds

---

docker/build.sh

Limit parallel docker buildx builds

---

docker/build.sh

Reduce maximum parallel docker buildx builds
